name = "Create Minecolonies"
author = "appkins"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3aa98aed7a6b9839f77fc6f24151968a3df0a7c6c292d7f2ef41636ee17ea39c"

[versions]
forge = "43.1.1"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
