name = "Above and Beyond"
author = "simibubi"
version = "1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7bfbc46ffa04b04657040b4f836769ec32beb4cfc9a1e5032f81be1fc764b9b"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
