name = "Above and Beyond"
author = "appkins"
version = "v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7532b4c2864c342a1cc30213ee7a2e772f5fd478bb9d1e5c952d7739a853245a"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"

[options]
no-internal-hashes = false
