name = "Create Minecolonies"
author = "appkins"
version = "1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8770cbef52586ab3947bcdb4b0c52650255ed7bbd220b9f6d1d91ae16a98109c"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
