name = "Above and Beyond"
author = "appkins"
version = "v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61ea569db76facb23a9afd295a50efe1c1d8a1e24bd701e34842d83456595fcf"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"

[options]
no-internal-hashes = false
