name = "Above and Beyond"
author = "simibubi"
version = "1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7e55d7eda1f55fd6633fedb76c2d7dbd150ba019e75445860ca4d0cce080fc6"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
