name = "Above and Beyond"
author = "appkins"
version = "v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce920583212083197320c99d92afd942a2f1871a504838d43fb26b23cf897bef"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"

[options]
no-internal-hashes = false
