name = "Above and Beyond"
author = "simibubi"
version = "1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7274af3a4c9936f3f3fa0cae4f58e4e13d7f6ced9550cddf0d4274371877924d"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
