name = "Above and Beyond"
author = "appkins"
version = "v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7e0776edc927d63135ceb6b0076786d34fa6205cc46518df40afc58fbf82f52"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"

[options]
no-internal-hashes = false
