name = "Above and Beyond"
author = "appkins"
version = "v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "099529f1630760f3429fa52148cf7e1d8e2113d29706666debd0c18e095a0fd2"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"

[options]
no-internal-hashes = false
