name = "Create Minecolonies"
author = "appkins"
version = "1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f900521b2a97bbdf50479764dfb8a4287a5b2f7dcb63af36f16a9132d93976b9"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
