name = "Above and Beyond"
author = "appkins"
version = "v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a42cb7984cfec2999983fb5595dacc344055ed2544631070ac0f30611d645d51"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
