name = "Create Minecolonies"
author = "appkins"
version = "1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26fe3537c0ad7172d4df631e3e84e582b13d020c0aa7c21939f64a8b5f33bb05"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
