name = "Above and Beyond"
author = "simibubi"
version = "1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77ed70babe3e9f607fd3201ada1a681601f0e071c7beb37394108bb4bdc0d3a2"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
