name = "Above and Beyond"
author = "simibubi"
version = "1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a331670177b3c741352e080c85f71452d352c2c787dc5ce3c05b70d848e5d52"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
